# Generated by Django 6.0.3 on 2026-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('rocket', models.CharField(blank=True, default='', max_length=256)),
                ('launch_provider', models.CharField(blank=True, default='', max_length=256)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('mission_description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['launch_date'],
            },
        ),
    ]
