# Generated by Django 6.0.3 on 2026-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='infographic_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='launch',
            name='mission_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='launch',
            name='orbit',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_location',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='launch',
            name='webcast_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='launch',
            name='wiki_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
