# Generated by Django 6.0.3 on 2026-04-19 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0004_launch_landing_pad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(blank=True, default='', max_length=128)),
                ('agency', models.CharField(blank=True, default='', max_length=256)),
                ('nationality', models.CharField(blank=True, default='', max_length=256)),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_image', models.URLField(blank=True, default='', max_length=1024)),
                ('wiki_url', models.URLField(blank=True, default='', max_length=1024)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(blank=True, default='', max_length=128)),
                ('orbit', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('owners', models.JSONField(blank=True, default=list)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='launch',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='launches', to='launches.astronaut'),
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ManyToManyField(related_name='expeditions', to='launches.astronaut')),
                ('space_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='launches.spacestation')),
            ],
        ),
        migrations.CreateModel(
            name='DockingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('docking_date', models.DateTimeField()),
                ('undocking_date', models.DateTimeField(blank=True, null=True)),
                ('docking_location', models.CharField(blank=True, default='', max_length=256)),
                ('spacecraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docking_events', to='launches.spacecraft')),
                ('space_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docking_events', to='launches.spacestation')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024)),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('news_site', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField()),
                ('launches', models.ManyToManyField(blank=True, related_name='articles', to='launches.launch')),
                ('space_stations', models.ManyToManyField(blank=True, related_name='articles', to='launches.spacestation')),
            ],
        ),
    ]
